# This is a basic workflow to help you get started with Actions

name: Avaliador

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
            python -m pip install --upgrade pip
            pip install openai
            pip install PyGithub
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: python ./scripts/main.py --token ${{ secrets.GIT_TOKEN }} --repo $GITHUB_REPOSITORY --pr $GITHUB_EVENT_NUMBER --openaikey ${{ secrets.OPENAI_KEY }} --model ${{secrets.OPENAI_MODEL}}
